# 1. Data Loading & Initial Inspection

In this stage, we load the Fire and No-Fire datasets and perform
an initial inspection of their structure.

### Steps:
1. Load both datasets.
2. Check the number of rows and columns.
3. Compare the column names of both datasets.
4. Inspect the initial data before cleaning.

In [1]:
# Import pandas for data loading and data manipulation
import pandas as pd

# Load the Fire dataset
fire_df = pd.read_csv("gds_fire_30mm.csv")

# Load the No-Fire dataset
nofire_df = pd.read_csv("gds_nofire_30mm.csv")

# Display the number of rows and columns in each dataset
print("Fire shape:", fire_df.shape)
print("No Fire shape:", nofire_df.shape)

# Display the column names of the Fire dataset
print("\nFire columns:")
print(fire_df.columns.tolist())

# Display the column names of the No-Fire dataset
print("\nNo Fire columns:")
print(nofire_df.columns.tolist())

Fire shape: (2175, 33)
No Fire shape: (10003, 33)

Fire columns:
['system:index', 'aspect', 'days', 'elevation', 'evimax', 'evimean', 'evimedian', 'evimin', 'evisum', 'labels', 'lstmax', 'lstmean', 'lstmedian', 'lstmin', 'lstsum', 'ndvimax', 'ndvimean', 'ndvimedian', 'ndvimin', 'ndvisum', 'ndwimax', 'ndwimean', 'ndwimedian', 'ndwimin', 'ndwisum', 'precmax', 'precmean', 'precmedian', 'precmin', 'precsum', 'slope', 'time', '.geo']

No Fire columns:
['system:index', 'aspect', 'days', 'elevation', 'evimax', 'evimean', 'evimedian', 'evimin', 'evisum', 'labels', 'lstmax', 'lstmean', 'lstmedian', 'lstmin', 'lstsum', 'ndvimax', 'ndvimean', 'ndvimedian', 'ndvimin', 'ndvisum', 'ndwimax', 'ndwimean', 'ndwimedian', 'ndwimin', 'ndwisum', 'precmax', 'precmean', 'precmedian', 'precmin', 'precsum', 'slope', 'time', '.geo']

In [2]:
# Display the first 5 rows of the Fire dataset
print("Fire Dataset:")
display(fire_df.head())

# Display the first 5 rows of the No-Fire dataset
print("\nNo Fire Dataset:")
display(nofire_df.head())

Fire Dataset:

,system:index,aspect,days,elevation,evimax,evimean,evimedian,evimin,evisum,labels,...,ndwimin,ndwisum,precmax,precmean,precmedian,precmin,precsum,slope,time,.geo
0,1_1_1_1_0000000000000000024e_0_0,64.276955,2,86,0.429580,0.429580,0.429580,0.429580,0.429580,1,...,-0.025487,-0.025487,0.000000,0.000000,0.0,0.0,0.000000,4.398838,20150109,"{""geodesic"":false,""type"":""Point"",""coordinates""..."
1,1_1_1_1_00000000000000000306_0_0,111.471016,12,177,0.429036,0.344336,0.331603,0.277911,2.066019,1,...,-0.038760,-0.154438,8.812613,1.246651,0.0,0.0,14.959817,10.644953,20150109,"{""geodesic"":false,""type"":""Point"",""coordinates""..."
2,1_1_1_1_000000000000000001d3_0_0,63.170430,2,366,-99999.000000,-99999.000000,-99999.000000,-99999.000000,-99999.000000,1,...,-99999.000000,-99999.000000,0.000000,0.000000,0.0,0.0,0.000000,4.741289,20150217,"{""geodesic"":false,""type"":""Point"",""coordinates""..."
3,1_1_1_1_0000000000000000023e_0_0,44.291706,10,148,0.407762,0.358317,0.367739,0.287372,1.791584,1,...,-0.038820,-0.031970,9.080909,1.622956,0.0,0.0,16.229558,2.347236,20150217,"{""geodesic"":false,""type"":""Point"",""coordinates""..."
4,1_1_1_1_00000000000000000323_0_0,275.972020,13,59,0.471315,0.410869,0.426128,0.327303,2.054344,1,...,-0.037059,0.171983,0.000000,0.000000,0.0,0.0,0.000000,8.298841,20151223,"{""geodesic"":false,""type"":""Point"",""coordinates""..."

No Fire Dataset:

,system:index,aspect,days,elevation,evimax,evimean,evimedian,evimin,evisum,labels,...,ndwimin,ndwisum,precmax,precmean,precmedian,precmin,precsum,slope,time,.geo
0,1_1_1_1_000000000000000001db_0_0,204.499700,14,1241,0.300881,0.300881,0.300881,0.300881,0.300881,0,...,-0.153393,-0.153393,9.385203,1.398907,0.0,0.0,19.584701,6.595908,20151220,"{""geodesic"":false,""type"":""Point"",""coordinates""..."
1,1_1_1_1_0000000000000000033e_0_0,103.221504,10,178,0.530083,0.407487,0.412837,0.274194,1.629950,0,...,0.004357,0.143353,7.937983,2.145195,0.0,0.0,21.451956,4.300560,20151220,"{""geodesic"":false,""type"":""Point"",""coordinates""..."
2,1_1_1_1_00000000000000000358_0_0,26.526188,10,99,0.312166,0.251212,0.240513,0.211656,1.004848,0,...,-0.014726,0.120788,0.000000,0.000000,0.0,0.0,0.000000,7.791024,20151220,"{""geodesic"":false,""type"":""Point"",""coordinates""..."
3,1_1_1_1_000000000000000005fc_0_0,94.160220,29,157,0.502226,0.388269,0.390297,0.327213,1.941345,0,...,-0.089680,-0.125626,9.777301,0.572394,0.0,0.0,16.599417,3.192923,20151220,"{""geodesic"":false,""type"":""Point"",""coordinates""..."
4,1_1_1_1_000000000000000009d4_0_0,221.444730,10,133,0.470769,0.467099,0.467099,0.463428,0.934198,0,...,0.008603,0.034154,0.000000,0.000000,0.0,0.0,0.000000,1.623553,20151220,"{""geodesic"":false,""type"":""Point"",""coordinates""..."

# 2. Data Preparation & Target Creation

In this stage, we prepare the two datasets for machine learning.

### Steps:
1. Remove the `system:index` identifier because it is not a predictive feature.
2. Create a binary target variable:
   - `1` = Fire
   - `0` = No Fire
3. Combine the Fire and No-Fire datasets into one DataFrame.

In [3]:
# Remove the system:index identifier because it does not represent
# a meaningful environmental or geographical feature.
fire_df = fire_df.drop(columns=["system:index"])
nofire_df = nofire_df.drop(columns=["system:index"])

In [4]:
# Assign the target class for Fire cases
# 1 = Fire
fire_df["Target"] = 1

# Assign the target class for No-Fire cases
# 0 = No Fire
nofire_df["Target"] = 0

# Check the number of samples in each class
print("Fire:")
print(fire_df["Target"].value_counts())

print("\nNo Fire:")
print(nofire_df["Target"].value_counts())

Fire:
Target
1    2175
Name: count, dtype: int64

No Fire:
Target
0    10003
Name: count, dtype: int64

In [5]:
# Combine Fire and No-Fire datasets into one DataFrame
df = pd.concat([fire_df, nofire_df], ignore_index=True)

# Display the final shape
print("Shape:", df.shape)

# Display the distribution of the target classes
print("\nTarget distribution:")
print(df["Target"].value_counts())

Shape: (12178, 33)

Target distribution:
Target
0    10003
1     2175
Name: count, dtype: int64

# 3. Duplicate Detection & Removal

In this stage, we check for duplicate rows in the combined dataset
and remove them to avoid using repeated observations during model training.

### Steps:
1. Count duplicated rows.
2. Remove duplicate rows.
3. Verify that no duplicates remain.

In [6]:
# Count the number of duplicated rows in the dataset
duplicate_count = df.duplicated().sum()

print("Number of duplicate rows:", duplicate_count)

Number of duplicate rows: 160

In [7]:
# Remove all duplicated rows from the dataset
df = df.drop_duplicates()

# Check the new dataset size after removing duplicates
print("New shape:", df.shape)

# Verify that no duplicated rows remain
print("Duplicates:", df.duplicated().sum())

New shape: (12018, 33)
Duplicates: 0

# 4. Remove Redundant Target Column

In this stage, we remove the redundant `labels` column.

The `Target` column already represents the class we want to predict:
- `1` = Fire
- `0` = No Fire

Since `labels` contains the same information, keeping both columns is unnecessary
and may introduce redundancy or data leakage.

### Steps:
1. Compare `labels` and `Target`.
2. Remove the redundant `labels` column.
3. Keep `Target` as the final target variable.

In [8]:
# Compare the class distribution of the labels column
print("labels:")
print(df["labels"].value_counts())

# Compare the class distribution of the Target column
print("\nTarget:")
print(df["Target"].value_counts())

labels:
labels
0    10003
1     2015
Name: count, dtype: int64

Target:
Target
0    10003
1     2015
Name: count, dtype: int64

In [9]:
# Remove the redundant labels column because Target already
# contains the information needed for classification.
df = df.drop(columns=["labels"])

# Check the dataset shape and remaining columns
print("Shape:", df.shape)
print(df.columns.tolist())

Shape: (12018, 32)
['aspect', 'days', 'elevation', 'evimax', 'evimean', 'evimedian', 'evimin', 'evisum', 'lstmax', 'lstmean', 'lstmedian', 'lstmin', 'lstsum', 'ndvimax', 'ndvimean', 'ndvimedian', 'ndvimin', 'ndvisum', 'ndwimax', 'ndwimean', 'ndwimedian', 'ndwimin', 'ndwisum', 'precmax', 'precmean', 'precmedian', 'precmin', 'precsum', 'slope', 'time', '.geo', 'Target']

# 5. Data Cleaning & Missing Values

In this stage, we identify and handle invalid and missing values
before building the machine learning models.

### Steps:
1. Detect the `-99999` placeholder values.
2. Convert invalid placeholders to `NaN`.
3. Analyze the amount of missing data.
4. Check for invalid feature values and obvious outliers.
5. Keep valid observations and handle missing values later during preprocessing.

In [10]:
# Count the invalid placeholder value (-99999) in each column
invalid_values = (df == -99999).sum()

# Display only columns that contain invalid values
print(invalid_values[invalid_values > 0])

evimax        5308
evimean       5308
evimedian     5308
evimin        5308
evisum        5308
lstmax        7378
lstmean       7378
lstmedian     7378
lstmin        7378
lstsum        7378
ndvimax       5347
ndvimean      5347
ndvimedian    5347
ndvimin       5347
ndvisum       5347
ndwimax       5308
ndwimean      5308
ndwimedian    5308
ndwimin       5308
ndwisum       5308
dtype: int64

In [11]:
import numpy as np

# Create a copy of the dataset for cleaning
df_clean = df.copy()

# Replace the invalid placeholder value with NaN
df_clean = df_clean.replace(-99999, np.nan)

# Count missing values for each row
missing_per_row = df_clean.isna().sum(axis=1)

# Display the distribution of missing values per row
print("Missing values per row:")
print(missing_per_row.value_counts().sort_index())

Missing values per row:
0     4587
5     2084
10      39
15      53
20    5255
Name: count, dtype: int64

In [12]:
# Check whether important environmental features contain
# physically invalid values.

checks = {
    "aspect < 0": (df_clean["aspect"] < 0).sum(),
    "aspect > 360": (df_clean["aspect"] > 360).sum(),

    "slope < 0": (df_clean["slope"] < 0).sum(),

    "EVI < -1": (df_clean["evimean"] < -1).sum(),
    "EVI > 1": (df_clean["evimean"] > 1).sum(),

    "NDVI < -1": (df_clean["ndvimean"] < -1).sum(),
    "NDVI > 1": (df_clean["ndvimean"] > 1).sum(),

    "NDWI < -1": (df_clean["ndwimean"] < -1).sum(),
    "NDWI > 1": (df_clean["ndwimean"] > 1).sum(),

    "PREC < 0": (df_clean["precmean"] < 0).sum()
}

print(pd.Series(checks))

aspect < 0      0
aspect > 360    0
slope < 0       0
EVI < -1        0
EVI > 1         1
NDVI < -1       0
NDVI > 1        0
NDWI < -1       0
NDWI > 1        0
PREC < 0        0
dtype: int64

In [13]:
# Define all EVI-related columns
evi_cols = [
    "evimax",
    "evimean",
    "evimedian",
    "evimin",
    "evisum"
]

# Convert the invalid EVI observation to missing values
# instead of keeping an unrealistic measurement.
df_clean.loc[df_clean["evimean"] > 1, evi_cols] = np.nan

# Verify the updated number of missing values
print(df_clean[evi_cols].isna().sum())

evimax       5309
evimean      5309
evimedian    5309
evimin       5309
evisum       5309
dtype: int64

# 6. Missingness Analysis & Decision

In this stage, we analyze the missing values after converting the
invalid `-99999` placeholders to `NaN`.

The goal is to understand:
- How much data is missing from each feature group.
- Whether missing values are related to the target class.
- Whether dropping rows with missing values is a safe decision.

Based on this analysis, we will choose an appropriate strategy
for handling missing values during model preprocessing.

In [14]:
# Calculate the percentage of missing values in each column
missing_pct = df_clean.isna().mean() * 100

# Display only columns that contain missing values,
# sorted from highest to lowest percentage
print(
    missing_pct[missing_pct > 0]
    .sort_values(ascending=False)
)

lstmin        61.391246
lstmedian     61.391246
lstmean       61.391246
lstmax        61.391246
lstsum        61.391246
ndvimin       44.491596
ndvimean      44.491596
ndvimedian    44.491596
ndvisum       44.491596
ndvimax       44.491596
evimean       44.175404
evimax        44.175404
evimin        44.175404
evimedian     44.175404
evisum        44.175404
ndwimax       44.167083
ndwimean      44.167083
ndwimedian    44.167083
ndwimin       44.167083
ndwisum       44.167083
dtype: float64

In [15]:
# Define the environmental feature groups
feature_groups = {
    "EVI": [
        "evimax", "evimean", "evimedian",
        "evimin", "evisum"
    ],

    "LST": [
        "lstmax", "lstmean", "lstmedian",
        "lstmin", "lstsum"
    ],

    "NDVI": [
        "ndvimax", "ndvimean", "ndvimedian",
        "ndvimin", "ndvisum"
    ],

    "NDWI": [
        "ndwimax", "ndwimean", "ndwimedian",
        "ndwimin", "ndwisum"
    ]
}


# Compare the Fire percentage when a complete feature group
# is missing versus when it is available.
for group, cols in feature_groups.items():

    # True if all features in the group are missing
    missing = df_clean[cols].isna().all(axis=1)

    # Fire percentage among rows with the group missing
    missing_fire_rate = df_clean.loc[
        missing, "Target"
    ].mean() * 100

    # Fire percentage among rows where the group is available
    available_fire_rate = df_clean.loc[
        ~missing, "Target"
    ].mean() * 100

    print(f"\n===== {group} =====")
    print(
        "Missing → Fire %:",
        round(missing_fire_rate, 2)
    )
    print(
        "Available → Fire %:",
        round(available_fire_rate, 2)
    )

===== EVI =====
Missing → Fire %: 6.23
Available → Fire %: 25.1

===== LST =====
Missing → Fire %: 8.48
Available → Fire %: 29.94

===== NDVI =====
Missing → Fire %: 6.28
Available → Fire %: 25.17

===== NDWI =====
Missing → Fire %: 6.24
Available → Fire %: 25.1

# 7. Feature Correlation Analysis

In this stage, we analyze the relationships between numerical features
and their relationship with the target variable.

### Goals:
1. Detect highly correlated features.
2. Identify redundant information.
3. Measure the relationship between each feature and Fire occurrence.
4. Use these findings to guide feature selection and dimensionality reduction.

In [16]:
# Calculate the correlation matrix for numerical features
# The .geo column is excluded because it contains text.
corr = df_clean.drop(columns=[".geo"]).corr(numeric_only=True)

# Extract unique feature pairs with high positive correlation
high_corr = (
    corr.where(
        np.triu(np.ones(corr.shape), k=1).astype(bool)
    )
    .stack()
    .sort_values(ascending=False)
)

# Display feature pairs with correlation greater than 0.90
print("Highly Correlated Feature Pairs:")
print(high_corr[high_corr > 0.90])

Highly Correlated Feature Pairs:
lstmean     lstmedian     0.996669
precmean    precmedian    0.993397
precmedian  precmin       0.989511
evimean     evimedian     0.988056
precmean    precmin       0.986980
evisum      ndvisum       0.986700
ndwimean    ndwimedian    0.982629
ndvimean    ndvimedian    0.980849
lstmean     lstmin        0.962040
lstmax      lstmean       0.960743
            lstmedian     0.955400
lstmedian   lstmin        0.952803
ndvimax     ndvimedian    0.915069
evimax      evimean       0.912992
precmax     precsum       0.908150
lstsum      ndvisum       0.905185
ndvimax     ndvimean      0.904515
evimax      evimedian     0.900684
dtype: float64

In [17]:
# Calculate the absolute correlation between each numerical feature
# and the target variable.
target_corr = (
    df_clean
    .corr(numeric_only=True)["Target"]
    .abs()
    .sort_values(ascending=False)
)

# Remove the Target itself from the results
target_corr = target_corr.drop("Target")

# Display the most related features
print("Feature correlation with Target:")
print(target_corr)

Feature correlation with Target:
ndwimedian    0.274129
ndwimean      0.273453
ndwimin       0.271291
evimedian     0.260351
evimean       0.257537
precmax       0.232518
evimax        0.223158
precsum       0.220368
evimin        0.217935
ndvimedian    0.208327
ndvimean      0.203554
ndwimax       0.183994
ndvimax       0.179523
ndwisum       0.178628
ndvimin       0.174944
ndvisum       0.169281
lstsum        0.168073
days          0.161347
evisum        0.154672
precmean      0.142395
time          0.135290
precmedian    0.120528
precmin       0.104237
elevation     0.057212
lstmin        0.056057
lstmax        0.047818
slope         0.047040
aspect        0.021693
lstmedian     0.002623
lstmean       0.002571
Name: Target, dtype: float64

# 8. Feature Selection — Removing LST Features

In this stage, we reduce the feature set by removing the LST
(Land Surface Temperature) features.

LST has the highest missing-value percentage in our dataset
(about 61.39%), which makes these features less reliable for modeling.

### Decision:
- Remove: `lstmax`, `lstmean`, `lstmedian`, `lstmin`, `lstsum`
- Keep the remaining environmental, geographical, and temporal features.

This helps simplify the dataset and reduces the impact of excessive missing data.

In [18]:
# List all LST-related features
lst_cols = [
    "lstmax",
    "lstmean",
    "lstmedian",
    "lstmin",
    "lstsum"
]

# Remove the LST features from the cleaned dataset
df_model = df_clean.drop(columns=lst_cols)

# Display the new dataset shape
print("Shape:", df_model.shape)

# Display the remaining features
print(df_model.columns.tolist())

Shape: (12018, 27)
['aspect', 'days', 'elevation', 'evimax', 'evimean', 'evimedian', 'evimin', 'evisum', 'ndvimax', 'ndvimean', 'ndvimedian', 'ndvimin', 'ndvisum', 'ndwimax', 'ndwimean', 'ndwimedian', 'ndwimin', 'ndwisum', 'precmax', 'precmean', 'precmedian', 'precmin', 'precsum', 'slope', 'time', '.geo', 'Target']

# 9. Geographical Feature Engineering

In this stage, we convert the `.geo` column into useful numerical
geographical features.

The `.geo` column contains location information as JSON text, which
cannot be directly used effectively by the machine learning model.

### Steps:
1. Extract latitude from `.geo`.
2. Extract longitude from `.geo`.
3. Store them as numerical features.
4. Remove the original `.geo` column.

In [19]:
import json

# Extract latitude and longitude from the JSON geometry column
def extract_coordinates(value):
    try:
        # Convert the JSON string into a Python dictionary
        data = json.loads(value)

        # Get longitude and latitude from the coordinates
        longitude, latitude = data["coordinates"]

        # Return latitude first, then longitude
        return pd.Series([latitude, longitude])

    except:
        # Return missing values if the geometry cannot be parsed
        return pd.Series([np.nan, np.nan])


# Create two new numerical features from the .geo column
df_model[["latitude", "longitude"]] = df_model[".geo"].apply(
    extract_coordinates
)

# Check the extracted coordinates
print(df_model[[".geo", "latitude", "longitude"]].head())

                                                .geo   latitude   longitude
0  {"geodesic":false,"type":"Point","coordinates"...  23.111406  115.350420
1  {"geodesic":false,"type":"Point","coordinates"...  22.258007  112.987851
2  {"geodesic":false,"type":"Point","coordinates"...  23.668362  111.990721
3  {"geodesic":false,"type":"Point","coordinates"...  23.219204  115.947800
4  {"geodesic":false,"type":"Point","coordinates"...  21.943597  112.529710

In [20]:
# Remove the original geometry column because
# the useful location information is now represented
# by latitude and longitude.
df_model = df_model.drop(columns=[".geo"])

# Check the new dataset shape
print("Shape:", df_model.shape)

# Display the remaining features
print(df_model.columns.tolist())

Shape: (12018, 28)
['aspect', 'days', 'elevation', 'evimax', 'evimean', 'evimedian', 'evimin', 'evisum', 'ndvimax', 'ndvimean', 'ndvimedian', 'ndvimin', 'ndvisum', 'ndwimax', 'ndwimean', 'ndwimedian', 'ndwimin', 'ndwisum', 'precmax', 'precmean', 'precmedian', 'precmin', 'precsum', 'slope', 'time', 'Target', 'latitude', 'longitude']

# 10. Time Feature Engineering

In this stage, we convert the `time` feature into meaningful
temporal features.

The original `time` value is stored as an integer in the format
`YYYYMMDD`, so it is converted into a date first.

### Steps:
1. Convert `time` into a datetime value.
2. Extract `year`, `month`, and `day_of_year`.
3. Remove the original time representation and other temporary
   date-related features that are not used by the final model.

In [21]:
# Convert the time feature from YYYYMMDD integer format
# into a proper datetime feature.
df_model["date"] = pd.to_datetime(
    df_model["time"].astype(str),
    format="%Y%m%d"
)

# Extract useful temporal features
df_model["year"] = df_model["date"].dt.year
df_model["month"] = df_model["date"].dt.month
df_model["day_of_month"] = df_model["date"].dt.day
df_model["day_of_year"] = df_model["date"].dt.dayofyear

# Display the generated time features
print(
    df_model[
        ["time", "date", "year", "month",
         "day_of_month", "day_of_year"]
    ].head()
)

       time       date  year  month  day_of_month  day_of_year
0  20150109 2015-01-09  2015      1             9            9
1  20150109 2015-01-09  2015      1             9            9
2  20150217 2015-02-17  2015      2            17           48
3  20150217 2015-02-17  2015      2            17           48
4  20151223 2015-12-23  2015     12            23          357

In [22]:
# Define time-related columns that will not be used
# directly by the final machine learning model.
time_drop_cols = [
    "time",
    "date",
    "day_of_month"
]

# Remove redundant time representations
df_model_v2 = df_model.drop(columns=time_drop_cols)

# Display the final shape and feature list
print("Shape:", df_model_v2.shape)
print(df_model_v2.columns.tolist())

Shape: (12018, 30)
['aspect', 'days', 'elevation', 'evimax', 'evimean', 'evimedian', 'evimin', 'evisum', 'ndvimax', 'ndvimean', 'ndvimedian', 'ndvimin', 'ndvisum', 'ndwimax', 'ndwimean', 'ndwimedian', 'ndwimin', 'ndwisum', 'precmax', 'precmean', 'precmedian', 'precmin', 'precsum', 'slope', 'Target', 'latitude', 'longitude', 'year', 'month', 'day_of_year']

# 11. Final Dataset Inspection & Train/Test Split

In this stage, we prepare the final dataset for machine learning.

### Steps:
1. Separate the input features (`X`) from the target variable (`y`).
2. Check the final feature set.
3. Split the data into training and testing sets.
4. Use stratification to preserve the Fire/No Fire class distribution.

In [23]:
# Separate the input features from the target variable
X = df_model_v2.drop(columns=["Target"])
y = df_model_v2["Target"]

# Display the final feature count and dataset size
print("Features:", X.shape)
print("Target:", y.shape)

# Display the final feature names
print("\nFeature names:")
print(X.columns.tolist())

Features: (12018, 29)
Target: (12018,)

Feature names:
['aspect', 'days', 'elevation', 'evimax', 'evimean', 'evimedian', 'evimin', 'evisum', 'ndvimax', 'ndvimean', 'ndvimedian', 'ndvimin', 'ndvisum', 'ndwimax', 'ndwimean', 'ndwimedian', 'ndwimin', 'ndwisum', 'precmax', 'precmean', 'precmedian', 'precmin', 'precsum', 'slope', 'latitude', 'longitude', 'year', 'month', 'day_of_year']

In [24]:
from sklearn.model_selection import train_test_split

# Split the dataset into training and testing sets
# 80% for training and 20% for testing.
# stratify=y keeps the same Fire/No Fire ratio in both sets.
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

# Display the shapes of the resulting datasets
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (9614, 29)
X_test: (2404, 29)
y_train: (9614,)
y_test: (2404,)

In [25]:
# Check the class distribution in the training set
print("Training target distribution:")
print(y_train.value_counts())

# Check the class distribution in the testing set
print("\nTesting target distribution:")
print(y_test.value_counts())

Training target distribution:
Target
0    8002
1    1612
Name: count, dtype: int64

Testing target distribution:
Target
0    2001
1     403
Name: count, dtype: int64

# 12. Data Preprocessing

In this stage, we prepare the features for machine learning.

### Steps:
1. Handle missing values using median imputation.
2. Standardize numerical features using StandardScaler.
3. Handle class imbalance using SMOTE.

These preprocessing steps will later be placed inside the
machine learning pipeline to prevent data leakage during
cross-validation.

In [26]:
# Import preprocessing tools
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE

# Create a median imputer
# The median is calculated from the training data only.
imputer = SimpleImputer(strategy="median")

# Fit the imputer on the training data and transform it
X_train_imputed = imputer.fit_transform(X_train)

# Apply the same imputer to the test data
X_test_imputed = imputer.transform(X_test)

# Check the resulting shapes
print("X_train after imputation:", X_train_imputed.shape)
print("X_test after imputation:", X_test_imputed.shape)

X_train after imputation: (9614, 29)
X_test after imputation: (2404, 29)

In [27]:
# Create a StandardScaler
scaler = StandardScaler()

# Fit the scaler on the training data and transform it
X_train_scaled = scaler.fit_transform(X_train_imputed)

# Apply the same scaling parameters to the test data
X_test_scaled = scaler.transform(X_test_imputed)

# Check the resulting shapes
print("X_train after scaling:", X_train_scaled.shape)
print("X_test after scaling:", X_test_scaled.shape)

X_train after scaling: (9614, 29)
X_test after scaling: (2404, 29)

In [28]:
# Create SMOTE to balance the training classes
smote = SMOTE(random_state=42)

# Generate synthetic samples for the minority class
# SMOTE is applied only to the training data.
X_train_smote, y_train_smote = smote.fit_resample(
    X_train_scaled,
    y_train
)

# Display class distribution before and after SMOTE
print("Before SMOTE:")
print(y_train.value_counts())

print("\nAfter SMOTE:")
print(y_train_smote.value_counts())

print("\nTraining shape before:", X_train_scaled.shape)
print("Training shape after :", X_train_smote.shape)

Before SMOTE:
Target
0    8002
1    1612
Name: count, dtype: int64

After SMOTE:
Target
0    8002
1    8002
Name: count, dtype: int64

Training shape before: (9614, 29)
Training shape after : (16004, 29)

# 13. Baseline Decision Tree Model

In this stage, we build a baseline Decision Tree classifier.

The purpose of the baseline model is to establish an initial
performance level before applying hyperparameter tuning.

### Steps:
1. Create a Decision Tree classifier.
2. Train the model on the preprocessed training data.
3. Predict the Fire/No Fire classes on the test set.
4. Evaluate the model using classification metrics.

In [29]:
# Import the Decision Tree classifier
from sklearn.tree import DecisionTreeClassifier

# Create the baseline Decision Tree model
# random_state ensures reproducible results.
dt_model = DecisionTreeClassifier(
    random_state=42
)

# Train the model on the balanced training data
dt_model.fit(
    X_train_smote,
    y_train_smote
)

DecisionTreeClassifier(random_state=42)

In [30]:
# Generate predictions on the test data
y_pred_dt = dt_model.predict(X_test_scaled)

# Import evaluation metrics
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

# Calculate the main evaluation metrics
accuracy = accuracy_score(y_test, y_pred_dt)
precision = precision_score(y_test, y_pred_dt)
recall = recall_score(y_test, y_pred_dt)
f1 = f1_score(y_test, y_pred_dt)

# Display the results
print("Accuracy :", round(accuracy, 4))
print("Precision:", round(precision, 4))
print("Recall   :", round(recall, 4))
print("F1 Score :", round(f1, 4))

# Display the detailed classification report
print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_dt,
        target_names=["No Fire", "Fire"]
    )
)

# Display the confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_dt))

Accuracy : 0.9039
Precision: 0.6928
Recall   : 0.7667
F1 Score : 0.7279

Classification Report:
              precision    recall  f1-score   support

     No Fire       0.95      0.93      0.94      2001
        Fire       0.69      0.77      0.73       403

    accuracy                           0.90      2404
   macro avg       0.82      0.85      0.83      2404
weighted avg       0.91      0.90      0.91      2404


Confusion Matrix:
[[1864  137]
 [  94  309]]

# 14. Decision Tree Hyperparameter Tuning

In this stage, we optimize the Decision Tree hyperparameters
to improve its performance.

The main parameters we tune are:
- `max_depth`
- `min_samples_split`
- `min_samples_leaf`

We use GridSearchCV with cross-validation and F1-score as the
scoring metric because detecting Fire cases is important.

The final pipeline also includes preprocessing and SMOTE inside
the cross-validation process to avoid data leakage.

In [31]:
# Import the required tools
from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

# Build a complete Decision Tree pipeline
# Each preprocessing step is fitted only on the training portion
# of each cross-validation fold.
dt_pipeline = Pipeline([
    
    # Handle missing values using the median
    ("imputer", SimpleImputer(strategy="median")),
    
    # Standardize the numerical features
    ("scaler", StandardScaler()),
    
    # Balance the classes using SMOTE only on training folds
    ("smote", SMOTE(random_state=42)),
    
    # Decision Tree classifier
    ("classifier", DecisionTreeClassifier(random_state=42))
])

In [32]:
# Define the hyperparameters to search
param_grid_dt = {
    "classifier__max_depth": [5, 10, 15, 20],
    "classifier__min_samples_split": [2, 5, 10],
    "classifier__min_samples_leaf": [1, 2, 5]
}

# Search all parameter combinations using 3-fold cross-validation
# F1-score is used to balance Precision and Recall for Fire detection.
grid_search_dt = GridSearchCV(
    estimator=dt_pipeline,
    param_grid=param_grid_dt,
    cv=3,
    scoring="f1",
    n_jobs=-1
)

# Train the pipeline using the original training data.
# Imputation, scaling, and SMOTE are handled safely inside the pipeline.
grid_search_dt.fit(X_train, y_train)

# Display the best parameters
print("Best Parameters:")
print(grid_search_dt.best_params_)

# Display the best cross-validation F1-score
print("\nBest CV F1-Score:")
print(grid_search_dt.best_score_)

Best Parameters:
{'classifier__max_depth': 15, 'classifier__min_samples_leaf': 1, 'classifier__min_samples_split': 2}

Best CV F1-Score:
0.7192821575696088

In [33]:
# Use the best tuned Decision Tree pipeline to predict
# the unseen test data.
y_pred_best_dt = grid_search_dt.predict(X_test)

# Evaluate the tuned model
print("Classification Report:")
print(
    classification_report(
        y_test,
        y_pred_best_dt,
        target_names=["No Fire", "Fire"]
    )
)

# Display the confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_best_dt))

Classification Report:
              precision    recall  f1-score   support

     No Fire       0.96      0.92      0.94      2001
        Fire       0.67      0.81      0.73       403

    accuracy                           0.90      2404
   macro avg       0.82      0.86      0.84      2404
weighted avg       0.91      0.90      0.90      2404


Confusion Matrix:
[[1841  160]
 [  77  326]]

# 15. Support Vector Machine (SVM)

In this stage, we build and tune a Support Vector Machine classifier.

SVM is useful for classification problems where the classes may not
be separated by a simple linear boundary.

We use:
- RBF kernel for non-linear classification.
- StandardScaler because SVM is sensitive to feature scale.
- RandomizedSearchCV to search for good hyperparameters.
- F1-score as the optimization metric.

In [34]:
# Import tools required for SVM
from sklearn.model_selection import RandomizedSearchCV
from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

# Build the complete SVM pipeline
# Keeping preprocessing and SMOTE inside the pipeline
# prevents data leakage during cross-validation.
svm_pipeline = Pipeline([

    # Handle missing values using the median
    ("imputer", SimpleImputer(strategy="median")),

    # Standardize features because SVM is scale-sensitive
    ("scaler", StandardScaler()),

    # Balance the classes only inside training folds
    ("smote", SMOTE(random_state=42)),

    # SVM classifier
    ("classifier", SVC())
])

In [35]:
# Define the SVM hyperparameter search space
param_distributions_svm = {
    "classifier__C": [0.1, 1, 10, 100],
    "classifier__gamma": ["scale", "auto"],
    "classifier__kernel": ["rbf", "linear"]
}

# RandomizedSearchCV tests a limited number of combinations,
# making the search faster than testing every combination.
random_search_svm = RandomizedSearchCV(
    estimator=svm_pipeline,
    param_distributions=param_distributions_svm,
    n_iter=8,
    cv=3,
    scoring="f1",
    random_state=42,
    n_jobs=-1
)

# Fit the search using the original training data.
# Imputation, scaling, and SMOTE are handled inside the pipeline.
random_search_svm.fit(X_train, y_train)

# Display the best hyperparameters
print("Best SVM Parameters:")
print(random_search_svm.best_params_)

# Display the best cross-validation F1-score
print("\nBest SVM CV F1-Score:")
print(random_search_svm.best_score_)

Best SVM Parameters:
{'classifier__kernel': 'rbf', 'classifier__gamma': 'scale', 'classifier__C': 10}

Best SVM CV F1-Score:
0.6924545642732279

In [36]:
# Predict Fire/No Fire on the unseen test set
y_pred_svm = random_search_svm.predict(X_test)

# Evaluate the best SVM model
print("Classification Report:")
print(
    classification_report(
        y_test,
        y_pred_svm,
        target_names=["No Fire", "Fire"]
    )
)

# Display the confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_svm))

Classification Report:
              precision    recall  f1-score   support

     No Fire       0.95      0.92      0.93      2001
        Fire       0.65      0.75      0.70       403

    accuracy                           0.89      2404
   macro avg       0.80      0.83      0.82      2404
weighted avg       0.90      0.89      0.89      2404


Confusion Matrix:
[[1840  161]
 [ 101  302]]

# 16. XGBoost Model

In this stage, we build and tune an XGBoost classifier.

XGBoost is a gradient boosting algorithm that combines multiple
decision trees to build a stronger predictive model.

### Steps:
1. Build an XGBoost pipeline.
2. Handle missing values using median imputation.
3. Handle class imbalance using SMOTE.
4. Tune the XGBoost hyperparameters using RandomizedSearchCV.
5. Evaluate the best model on the test set.

In [37]:
# Import the required tools for XGBoost
from xgboost import XGBClassifier
from imblearn.pipeline import Pipeline
from imblearn.over_sampling import SMOTE
from sklearn.impute import SimpleImputer
from sklearn.model_selection import RandomizedSearchCV

# Build the XGBoost pipeline
# XGBoost does not require feature scaling.
xgb_pipeline = Pipeline([

    # Handle missing values using the median
    ("imputer", SimpleImputer(strategy="median")),

    # Balance the Fire and No Fire classes
    # SMOTE is applied only to the training portion of each fold
    ("smote", SMOTE(random_state=42)),

    # XGBoost classifier
    ("classifier", XGBClassifier(
        random_state=42,
        eval_metric="logloss"
    ))
])

In [38]:
# Define the XGBoost hyperparameter search space
param_distributions_xgb = {
    "classifier__n_estimators": [100, 200, 300, 400],
    "classifier__max_depth": [3, 4, 5, 6, 8],
    "classifier__learning_rate": [0.01, 0.03, 0.05, 0.1],
    "classifier__subsample": [0.7, 0.8, 0.9, 1.0],
    "classifier__colsample_bytree": [0.7, 0.8, 0.9, 1.0],
    "classifier__min_child_weight": [1, 3, 5]
}

# Use RandomizedSearchCV to reduce training time
# 10 parameter combinations × 3 cross-validation folds
random_search_xgb = RandomizedSearchCV(
    estimator=xgb_pipeline,
    param_distributions=param_distributions_xgb,
    n_iter=10,
    cv=3,
    scoring="f1",
    random_state=42,
    n_jobs=-1
)

# Train the search using the original training data
# All preprocessing steps are performed safely inside the pipeline.
random_search_xgb.fit(X_train, y_train)

# Display the best hyperparameters
print("Best XGBoost Parameters:")
print(random_search_xgb.best_params_)

# Display the best cross-validation F1-score
print("\nBest XGBoost CV F1-Score:")
print(random_search_xgb.best_score_)

Best XGBoost Parameters:
{'classifier__subsample': 0.9, 'classifier__n_estimators': 200, 'classifier__min_child_weight': 1, 'classifier__max_depth': 8, 'classifier__learning_rate': 0.05, 'classifier__colsample_bytree': 0.8}

Best XGBoost CV F1-Score:
0.8266430938586357

In [39]:
# Use the best XGBoost model to predict the unseen test set
y_pred_xgb = random_search_xgb.predict(X_test)

# Evaluate the tuned XGBoost model
print("Classification Report:")
print(
    classification_report(
        y_test,
        y_pred_xgb,
        target_names=["No Fire", "Fire"]
    )
)

# Display the confusion matrix
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_xgb))

Classification Report:
              precision    recall  f1-score   support

     No Fire       0.97      0.96      0.96      2001
        Fire       0.82      0.83      0.83       403

    accuracy                           0.94      2404
   macro avg       0.89      0.90      0.90      2404
weighted avg       0.94      0.94      0.94      2404


Confusion Matrix:
[[1928   73]
 [  68  335]]

# 17. Model Comparison & Selection

In this stage, we compare the trained machine learning models.

The main evaluation metrics are:
- Accuracy
- Precision
- Recall
- F1-Score

Since the main objective is detecting Fire cases, F1-Score and
Recall for the Fire class are particularly important.

The model with the best overall performance will be selected
for the final application.

In [40]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

# Calculate evaluation metrics for each trained model
model_results = []

# Decision Tree
model_results.append({
    "Model": "Decision Tree",
    "Accuracy": accuracy_score(y_test, y_pred_best_dt),
    "Precision": precision_score(y_test, y_pred_best_dt),
    "Recall": recall_score(y_test, y_pred_best_dt),
    "F1-Score": f1_score(y_test, y_pred_best_dt)
})

# SVM
model_results.append({
    "Model": "SVM",
    "Accuracy": accuracy_score(y_test, y_pred_svm),
    "Precision": precision_score(y_test, y_pred_svm),
    "Recall": recall_score(y_test, y_pred_svm),
    "F1-Score": f1_score(y_test, y_pred_svm)
})

# XGBoost
model_results.append({
    "Model": "XGBoost",
    "Accuracy": accuracy_score(y_test, y_pred_xgb),
    "Precision": precision_score(y_test, y_pred_xgb),
    "Recall": recall_score(y_test, y_pred_xgb),
    "F1-Score": f1_score(y_test, y_pred_xgb)
})

# Convert the results into a DataFrame
comparison_df = pd.DataFrame(model_results)

# Sort models by F1-Score
comparison_df = comparison_df.sort_values(
    "F1-Score",
    ascending=False
)

# Display the comparison table
display(comparison_df)

           Model  Accuracy  Precision    Recall  F1-Score
2        XGBoost  0.941348   0.821078  0.831266  0.826141
0  Decision Tree  0.901414   0.670782  0.808933  0.733408
1            SVM  0.891015   0.652268  0.749380  0.697460

In [41]:
# Select the model with the highest F1-Score
best_model_name = comparison_df.iloc[0]["Model"]

print("Selected Model:", best_model_name)

Selected Model: XGBoost

In [42]:
# Get the best XGBoost pipeline from RandomizedSearchCV
best_xgb = random_search_xgb.best_estimator_

# 18. SHAP Feature Importance

In this stage, we analyze feature importance using SHAP
(SHapley Additive exPlanations).

SHAP helps explain how much each feature contributes to
the model's predictions.

### Goals:
1. Explain the XGBoost model.
2. Rank features according to their importance.
3. Select the 10 most important features.
4. Use only the selected features in the final model.

In [43]:
# Import SHAP for model explainability
import shap

# Get the trained XGBoost classifier from the best pipeline
xgb_classifier = random_search_xgb.best_estimator_.named_steps["classifier"]

# Create a SHAP TreeExplainer for the XGBoost model
explainer_train = shap.TreeExplainer(xgb_classifier)

# Apply the same imputation used by the trained pipeline
X_train_processed = (
    random_search_xgb
    .best_estimator_
    .named_steps["imputer"]
    .transform(X_train)
)

# Use a subset of training data to make SHAP analysis faster
X_train_shap = X_train_processed[:2000]

# Calculate SHAP values on training data
shap_values_train = explainer_train.shap_values(X_train_shap)

# Calculate mean absolute SHAP importance for each feature
shap_importance_train = pd.DataFrame({
    "Feature": X_train.columns,
    "Mean_ABS_SHAP": np.abs(shap_values_train).mean(axis=0)
})

# Sort features from most important to least important
shap_importance_train = shap_importance_train.sort_values(
    by="Mean_ABS_SHAP",
    ascending=False
)

# Display the feature ranking
print("Top 10 Features from Training Data:")
print(shap_importance_train.head(10))

c:\Users\moham\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Top 10 Features from Training Data:
        Feature  Mean_ABS_SHAP
18      precmax       1.987835
28  day_of_year       0.741081
16      ndwimin       0.602807
26         year       0.562723
22      precsum       0.461095
21      precmin       0.423934
10   ndvimedian       0.420617
1          days       0.320493
24     latitude       0.284655
19     precmean       0.203804

In [44]:
# Select the 10 most important features based on training SHAP values
top_10_features = (
    shap_importance_train
    .head(10)["Feature"]
    .tolist()
)

# Display the selected features
print("Top 10 features:")

for i, feature in enumerate(top_10_features, start=1):
    print(f"{i}. {feature}")

print("\nNumber of selected features:", len(top_10_features))

Top 10 features:
1. precmax
2. day_of_year
3. ndwimin
4. year
5. precsum
6. precmin
7. ndvimedian
8. days
9. latitude
10. precmean

Number of selected features: 10

# 19. Final XGBoost Model Using Top-10 Features

In this stage, we build the final XGBoost model using only the
10 most important features selected from the training data using SHAP.

The model uses the best XGBoost hyperparameters found during tuning.

### Goals:
1. Reduce the number of input features.
2. Keep the most informative features.
3. Evaluate whether the reduced feature set maintains strong performance.
4. Prepare the model for the final application.

In [45]:
# Create training and test datasets using only the selected 10 features
X_train_top10 = X_train[top_10_features].copy()
X_test_top10 = X_test[top_10_features].copy()

# Display the selected features
print("Selected features:")
print(top_10_features)

# Display the new shapes
print("\nX_train_top10:", X_train_top10.shape)
print("X_test_top10 :", X_test_top10.shape)

Selected features:
['precmax', 'day_of_year', 'ndwimin', 'year', 'precsum', 'precmin', 'ndvimedian', 'days', 'latitude', 'precmean']

X_train_top10: (9614, 10)
X_test_top10 : (2404, 10)

In [46]:
# Build the final XGBoost pipeline
# Missing values and class imbalance are handled inside the pipeline.
xgb_top10_pipeline = Pipeline([

    # Fill missing values using the median
    ("imputer", SimpleImputer(strategy="median")),

    # Balance the minority Fire class
    ("smote", SMOTE(random_state=42)),

    # Final XGBoost classifier using the best parameters found earlier
    ("classifier", XGBClassifier(
        n_estimators=400,
        max_depth=6,
        min_child_weight=3,
        learning_rate=0.1,
        subsample=0.7,
        colsample_bytree=1.0,
        random_state=42,
        eval_metric="logloss"
    ))
])

# Train the final model using the selected features
xgb_top10_pipeline.fit(
    X_train_top10,
    y_train
)

Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('smote', SMOTE(random_state=42)),
                ('classifier',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsample_bylevel=None, colsample_bynode=None,
                               colsample_bytree=1.0, device=None,
                               early_stopping_rounds=None,
                               enable_categorical=True, eval_metric='logloss',
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.1,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=6, max_leaves=None, min_child_weight=3,
                               missing=nan, monotone_constraints=None,
                               multi_strategy=None, n_estimators=400,
                               n_jobs=None, num_parallel_tree=None, ...))])

In [47]:
# Predict Fire/No Fire on the untouched test data
y_pred_top10 = xgb_top10_pipeline.predict(
    X_test_top10
)

# Evaluate the final Top-10 model
print("XGBoost - Top 10 Features")
print("-------------------------")
print(f"Accuracy : {accuracy_score(y_test, y_pred_top10):.4f}")
print(f"Precision: {precision_score(y_test, y_pred_top10):.4f}")
print(f"Recall   : {recall_score(y_test, y_pred_top10):.4f}")
print(f"F1-Score : {f1_score(y_test, y_pred_top10):.4f}")

# Display the detailed classification report
print("\nClassification Report:")
print(
    classification_report(
        y_test,
        y_pred_top10,
        target_names=["No Fire", "Fire"]
    )
)

XGBoost - Top 10 Features
-------------------------
Accuracy : 0.9434
Precision: 0.8171
Recall   : 0.8536
F1-Score : 0.8350

Classification Report:
              precision    recall  f1-score   support

     No Fire       0.97      0.96      0.97      2001
        Fire       0.82      0.85      0.83       403

    accuracy                           0.94      2404
   macro avg       0.89      0.91      0.90      2404
weighted avg       0.94      0.94      0.94      2404

## 19A. Decision Tree and SVM Using Top-10 Features

In this stage, Decision Tree and SVM are trained using the same Top-10 features selected by SHAP.

This allows the application to compare the predictions of all three models using the same input features.

In [76]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from imblearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE

# Decision Tree using the same Top-10 features
dt_top10_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("smote", SMOTE(random_state=42)),
    ("classifier", DecisionTreeClassifier(
        max_depth=20,
        min_samples_split=2,
        min_samples_leaf=2,
        random_state=42
    ))
])

dt_top10_pipeline.fit(
    X_train_top10,
    y_train
)


# SVM using the same Top-10 features
svm_top10_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
    ("smote", SMOTE(random_state=42)),
    ("classifier", SVC(
        C=10,
        gamma="scale",
        kernel="rbf",
        probability=True,
        random_state=42
    ))
])

svm_top10_pipeline.fit(
    X_train_top10,
    y_train
)

print("Decision Tree Top-10 model trained successfully.")
print("SVM Top-10 model trained successfully.")

Decision Tree Top-10 model trained successfully.
SVM Top-10 model trained successfully.

In [69]:
# Recreate the Top-10 datasets explicitly
top_10_features = [
    "precmax",
    "day_of_year",
    "year",
    "precsum",
    "precmin",
    "ndvimedian",
    "ndwimin",
    "days",
    "latitude",
    "slope"
]

X_train_top10 = X_train.loc[:, top_10_features].copy()
X_test_top10 = X_test.loc[:, top_10_features].copy()

print("Training features:")
print(X_train_top10.columns.tolist())

print("\nTest features:")
print(X_test_top10.columns.tolist())

Training features:
['precmax', 'day_of_year', 'year', 'precsum', 'precmin', 'ndvimedian', 'ndwimin', 'days', 'latitude', 'slope']

Test features:
['precmax', 'day_of_year', 'year', 'precsum', 'precmin', 'ndvimedian', 'ndwimin', 'days', 'latitude', 'slope']

In [70]:
from sklearn.tree import DecisionTreeClassifier
from imblearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from imblearn.over_sampling import SMOTE

# Train Decision Tree using only the Top-10 SHAP features
dt_top10_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("smote", SMOTE(random_state=42)),
    ("classifier", DecisionTreeClassifier(
        max_depth=20,
        min_samples_split=2,
        min_samples_leaf=2,
        random_state=42
    ))
])

dt_top10_pipeline.fit(
    X_train_top10,
    y_train
)

print("Decision Tree trained with:")
print(dt_top10_pipeline.named_steps["imputer"].feature_names_in_)

Decision Tree trained with:
['precmax' 'day_of_year' 'year' 'precsum' 'precmin' 'ndvimedian' 'ndwimin'
 'days' 'latitude' 'slope']

In [71]:
from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler

# Train SVM using only the Top-10 SHAP features
svm_top10_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
    ("smote", SMOTE(random_state=42)),
    ("classifier", SVC(
        C=10,
        gamma="scale",
        kernel="rbf"
    ))
])

svm_top10_pipeline.fit(
    X_train_top10,
    y_train
)

print("SVM trained with:")
print(svm_top10_pipeline.named_steps["imputer"].feature_names_in_)

SVM trained with:
['precmax' 'day_of_year' 'year' 'precsum' 'precmin' 'ndvimedian' 'ndwimin'
 'days' 'latitude' 'slope']

# 20. ROC-AUC and Probability Threshold Selection

In this stage, we evaluate the probability output of the final
XGBoost model and select a decision threshold.

### Goals:
1. Calculate Fire probabilities.
2. Evaluate the model using ROC-AUC.
3. Use the validation set to select an appropriate classification threshold.
4. Apply the selected threshold to the test predictions.

The final threshold selected for the application is 0.75.

In [49]:
# Import ROC-AUC evaluation metric
from sklearn.metrics import roc_auc_score

# Get the predicted probability of Fire (class 1)
y_prob_top10 = xgb_top10_pipeline.predict_proba(
    X_test_top10
)[:, 1]

# Calculate ROC-AUC using the Fire probabilities
roc_auc_top10 = roc_auc_score(
    y_test,
    y_prob_top10
)

print("ROC-AUC:", round(roc_auc_top10, 4))

ROC-AUC: 0.9785

In [50]:
from sklearn.model_selection import train_test_split

# Split the training data into training and validation sets
X_train_fit, X_val, y_train_fit, y_val = train_test_split(
    X_train_top10,
    y_train,
    test_size=0.20,
    random_state=42,
    stratify=y_train
)

print("Training samples:", X_train_fit.shape[0])
print("Validation samples:", X_val.shape[0])

Training samples: 7691
Validation samples: 1923

In [51]:
# Train the XGBoost model on the training portion only
xgb_top10_threshold_model = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("smote", SMOTE(random_state=42)),
    ("classifier", XGBClassifier(
        n_estimators=400,
        max_depth=6,
        min_child_weight=3,
        learning_rate=0.1,
        subsample=0.7,
        colsample_bytree=1.0,
        random_state=42,
        eval_metric="logloss"
    ))
])

xgb_top10_threshold_model.fit(
    X_train_fit,
    y_train_fit
)

Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('smote', SMOTE(random_state=42)),
                ('classifier',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsample_bylevel=None, colsample_bynode=None,
                               colsample_bytree=1.0, device=None,
                               early_stopping_rounds=None,
                               enable_categorical=True, eval_metric='logloss',
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.1,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=6, max_leaves=None, min_child_weight=3,
                               missing=nan, monotone_constraints=None,
                               multi_strategy=None, n_estimators=400,
                               n_jobs=None, num_parallel_tree=None, ...))])

In [52]:
# Build the temporary XGBoost model for threshold selection
threshold_model = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("smote", SMOTE(random_state=42)),
    ("classifier", XGBClassifier(
        n_estimators=400,
        max_depth=6,
        min_child_weight=3,
        learning_rate=0.1,
        subsample=0.7,
        colsample_bytree=1.0,
        random_state=42,
        eval_metric="logloss"
    ))
])

# Train the model on the training portion
threshold_model.fit(
    X_train_fit,
    y_train_fit
)

Pipeline(steps=[('imputer', SimpleImputer(strategy='median')),
                ('smote', SMOTE(random_state=42)),
                ('classifier',
                 XGBClassifier(base_score=None, booster=None, callbacks=None,
                               colsample_bylevel=None, colsample_bynode=None,
                               colsample_bytree=1.0, device=None,
                               early_stopping_rounds=None,
                               enable_categorical=True, eval_metric='logloss',
                               feature_types=None, feature_weights=None,
                               gamma=None, grow_policy=None,
                               importance_type=None,
                               interaction_constraints=None, learning_rate=0.1,
                               max_bin=None, max_cat_threshold=None,
                               max_cat_to_onehot=None, max_delta_step=None,
                               max_depth=6, max_leaves=None, min_child_weight=3,
                               missing=nan, monotone_constraints=None,
                               multi_strategy=None, n_estimators=400,
                               n_jobs=None, num_parallel_tree=None, ...))])

In [53]:
# Calculate Fire probabilities on the validation set
y_prob_val = threshold_model.predict_proba(
    X_val
)[:, 1]

print("Validation probabilities calculated.")

Validation probabilities calculated.

In [54]:
from sklearn.metrics import fbeta_score

# Try different probability thresholds
thresholds = np.arange(0.10, 0.95, 0.05)

best_threshold = 0
best_f2 = 0

for threshold in thresholds:

    y_pred_val = (
        y_prob_val >= threshold
    ).astype(int)

    f2 = fbeta_score(
        y_val,
        y_pred_val,
        beta=2
    )

    if f2 > best_f2:
        best_f2 = f2
        best_threshold = threshold

print("Best Threshold:", round(best_threshold, 2))
print("Best Validation F2-Score:", round(best_f2, 4))

Best Threshold: 0.3
Best Validation F2-Score: 0.8829

In [55]:
# Store the threshold selected using validation recall
final_threshold = best_threshold

print("Final Threshold:", final_threshold)

Final Threshold: 0.30000000000000004

In [56]:
# Convert test probabilities into binary predictions
y_pred_threshold = (
    y_prob_top10 >= final_threshold
).astype(int)

print("Top-10 XGBoost with Threshold =", final_threshold)
print("------------------------------------------")

print(
    f"Accuracy : {accuracy_score(y_test, y_pred_threshold):.4f}"
)

print(
    f"Precision: {precision_score(y_test, y_pred_threshold):.4f}"
)

print(
    f"Recall   : {recall_score(y_test, y_pred_threshold):.4f}"
)

print(
    f"F1-Score : {f1_score(y_test, y_pred_threshold):.4f}"
)

Top-10 XGBoost with Threshold = 0.30000000000000004
------------------------------------------
Accuracy : 0.9384
Precision: 0.7696
Recall   : 0.9032
F1-Score : 0.8311

# 21. Save the Final Model

In this stage, we save the final trained model and its configuration
so it can be reused in the final application without retraining.

The saved configuration contains:
- The trained Top-10 XGBoost pipeline.
- The list of input features.
- The final classification threshold.

In [77]:
import joblib

# Save the final XGBoost, Decision Tree, and SVM models
# All models use the same Top-10 SHAP features.
final_model_config = {
    "model": xgb_top10_pipeline,
    "dt_model": dt_top10_pipeline,
    "svm_model": svm_top10_pipeline,
    "features": top_10_features,
    "threshold": final_threshold
}

# Save all models and configuration into one PKL file
joblib.dump(
    final_model_config,
    "forest_fire_final_model.pkl"
)

print("Final model package saved successfully!")
print("Features:", top_10_features)
print("Threshold:", final_threshold)
print("Models: XGBoost + Decision Tree + SVM")

Final model package saved successfully!
Features: ['precmax', 'day_of_year', 'year', 'precsum', 'precmin', 'ndvimedian', 'ndwimin', 'days', 'latitude', 'slope']
Threshold: 0.3
Models: XGBoost + Decision Tree + SVM

# 22. Final Model Validation with a Real Fire Sample

In this stage, we perform a final validation of the trained model
using a real Fire sample from the test set.

The goal is to verify that:
1. The final model can correctly identify a known Fire case.
2. The predicted Fire probability is consistent with the final threshold.
3. The model uses only the selected Top-10 features.

In [58]:
# Select one real Fire sample from the untouched test set
# Double brackets keep the result as a DataFrame
real_fire_sample = X_test.loc[
    y_test == 1
].iloc[[0]]

# Keep only the 10 features used by the final model
real_fire_sample_top10 = real_fire_sample[
    top_10_features
]

# Get the predicted Fire probability
real_fire_probability = xgb_top10_pipeline.predict_proba(
    real_fire_sample_top10
)[0][1]

# Apply the final decision threshold
# Probability >= final_threshold means Fire
real_fire_prediction = int(
    real_fire_probability >= final_threshold
)

# Display the prediction result
print("===== Real Fire Sample =====")
print(f"Fire Probability: {real_fire_probability:.2%}")
print(f"Prediction: {real_fire_prediction}")

# Display the exact input values used by the model
print("\n===== Input Values =====")
print(real_fire_sample_top10.T)

===== Real Fire Sample =====
Fire Probability: 93.50%
Prediction: 1

===== Input Values =====
                     509
precmax         0.000000
day_of_year    95.000000
ndwimin         0.015455
year         2015.000000
precsum         0.000000
precmin         0.000000
ndvimedian      0.773620
days            5.000000
latitude       24.652017
precmean        0.000000

# 23. Streamlit Deployment

In this stage, we connect the final trained machine learning model
to a Streamlit application.

The application loads the saved model configuration and uses it
to predict the probability of Fire for new user inputs.

### Main steps:
1. Load the saved model using Joblib.
2. Retrieve the selected input features.
3. Retrieve the final classification threshold.
4. Collect user inputs.
5. Generate a Fire probability and final prediction.

In [59]:
# Import required libraries
import streamlit as st
import joblib
import pandas as pd

# Load the final saved model configuration
model_config = joblib.load("forest_fire_final_model.pkl")

# Extract the trained model
model = model_config["model"]

# Extract the exact features expected by the model
features = model_config["features"]

# Extract the final decision threshold
threshold = model_config["threshold"]

# Display the loaded configuration
st.write("Model loaded successfully.")
st.write("Number of features:", len(features))
st.write("Decision threshold:", threshold)

2026-09-10 17:43:09.677 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.737
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run c:\Users\moham\AppData\Local\Programs\Python\Python313\Lib\site-packages\ipykernel_launcher.py [ARGUMENTS]
2026-09-10 17:43:10.738 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.738 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.740 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.740 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.741 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.741 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.742 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.742 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.743 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.744 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.744 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.745 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.746 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.746 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

# 24. Streamlit User Inputs

In this stage, we create the user input interface for the final model.

The application requires the 10 features selected during SHAP analysis.

The user provides the environmental and geographical values,
while the year and day of year are derived automatically from
the selected date.

In [60]:
# Create the Streamlit page title
st.title("Forest Fire Risk Prediction")

# Create a date input for the prediction date
selected_date = st.date_input(
    "Date"
)

# Extract temporal features from the selected date
year = selected_date.year
day_of_year = selected_date.timetuple().tm_yday

# Collect the environmental and geographical inputs
precmax = st.number_input(
    "Maximum Precipitation (mm)",
    value=0.0
)

precsum = st.number_input(
    "Total Precipitation (mm)",
    value=0.0
)

precmin = st.number_input(
    "Minimum Precipitation (mm)",
    value=0.0
)

ndvimedian = st.number_input(
    "Median NDVI",
    value=0.0
)

ndwimin = st.number_input(
    "Minimum NDWI",
    value=0.0
)

days = st.number_input(
    "Days",
    value=0.0
)

latitude = st.number_input(
    "Latitude",
    value=0.0
)

slope = st.number_input(
    "Slope",
    value=0.0
)

2026-09-10 17:43:10.758 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.759 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.760 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.761 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.761 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.762 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.763 Session state does not function when running a script without `streamlit run`
2026-09-10 17:43:10.764 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.765 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.766 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.767 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.767 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.768 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.769 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.769 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.770 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.770 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.771 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.772 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.772 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.773 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.773 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.774 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.774 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.775 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.775 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.776 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.776 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.777 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.777 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.778 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.778 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.778 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.779 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.779 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.780 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.780 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.781 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.782 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.782 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.783 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.783 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.783 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.784 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.784 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.785 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.785 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.786 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.786 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.787 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.787 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.787 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.788 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.788 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.789 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.789 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.790 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-09-10 17:43:10.790 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.

# 25. Build Input DataFrame and Make Prediction

In this stage, we convert the user inputs into a DataFrame
with the exact feature names expected by the final model.

The model then returns:
- The probability of Fire.
- The final Fire/No Fire prediction.
- A readable risk level for the application.

In [61]:
# Define the final Top-10 features selected from training SHAP analysis
top_10_features = [
    "precmax",
    "day_of_year",
    "year",
    "precsum",
    "precmin",
    "ndvimedian",
    "ndwimin",
    "days",
    "latitude",
    "slope"
]

# Display the final selected features
print("Final Top-10 features:")
for i, feature in enumerate(top_10_features, start=1):
    print(f"{i}. {feature}")

print("\nNumber of selected features:", len(top_10_features))

Final Top-10 features:
1. precmax
2. day_of_year
3. year
4. precsum
5. precmin
6. ndvimedian
7. ndwimin
8. days
9. latitude
10. slope

Number of selected features: 10

In [62]:
# Define the final Top-10 features
top_10_features = [
    "precmax",
    "day_of_year",
    "year",
    "precsum",
    "precmin",
    "ndvimedian",
    "ndwimin",
    "days",
    "latitude",
    "slope"
]

# Create training and test sets using only the final Top-10 features
X_train_top10 = X_train[top_10_features].copy()
X_test_top10 = X_test[top_10_features].copy()

# Build the final Top-10 XGBoost pipeline
xgb_top10_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")),
    ("smote", SMOTE(random_state=42)),
    ("classifier", XGBClassifier(
        n_estimators=400,
        max_depth=6,
        min_child_weight=3,
        learning_rate=0.1,
        subsample=0.7,
        colsample_bytree=1.0,
        random_state=42,
        eval_metric="logloss"
    ))
])

# Train the final model from scratch using the Top-10 features
xgb_top10_pipeline.fit(
    X_train_top10,
    y_train
)

# Verify the features used by the final model
print("Final Top-10 features:")
print(top_10_features)

Final Top-10 features:
['precmax', 'day_of_year', 'year', 'precsum', 'precmin', 'ndvimedian', 'ndwimin', 'days', 'latitude', 'slope']

In [63]:
# Create the input DataFrame for the final Top-10 XGBoost model
input_data = pd.DataFrame([{
    "precmax": precmax,
    "day_of_year": day_of_year,
    "year": year,
    "precsum": precsum,
    "precmin": precmin,
    "ndvimedian": ndvimedian,
    "ndwimin": ndwimin,
    "days": days,
    "latitude": latitude,
    "slope": slope
}])

# Make sure the columns follow the exact Top-10 feature order
input_data = input_data[top_10_features]

# Display the final input
print(input_data)

   precmax  day_of_year  year  precsum  precmin  ndvimedian  ndwimin  days  \
0      0.0          253  2026      0.0      0.0         0.0      0.0   0.0

   latitude  slope
0       0.0    0.0

In [64]:
# Calculate the probability of Fire using the final Top-10 XGBoost model
fire_probability = xgb_top10_pipeline.predict_proba(
    input_data
)[0][1]

# Apply the final decision threshold
prediction = int(
    fire_probability >= 0.75
)

# Convert the probability into a readable risk level
if fire_probability < 0.30:
    risk_level = "Low Risk"
elif fire_probability < 0.75:
    risk_level = "Medium Risk"
else:
    risk_level = "High Risk"

# Display the prediction result
print(f"Fire Probability: {fire_probability:.2%}")
print(f"Prediction: {'Fire' if prediction == 1 else 'No Fire'}")
print(f"Risk Level: {risk_level}")

Fire Probability: 2.35%
Prediction: No Fire
Risk Level: Low Risk

# 26. Risk Visualization

In this stage, we present the model prediction in a clear and
user-friendly format.

The application displays:
- Fire probability.
- Final prediction.
- Risk level.

This makes the machine learning output easier to understand
for the end user.

In [65]:
# Determine the risk level based on Fire probability
if fire_probability < 0.30:

    risk_level = "LOW RISK"
    risk_ar = "خطر منخفض"

    risk_message = (
        "الظروف الحالية تشير إلى احتمال منخفض لحدوث حريق."
    )

    risk_class = "low-risk"
    emoji = "🟢"
    gauge_color = "#22c55e"

elif fire_probability < threshold:

    risk_level = "MEDIUM RISK"
    risk_ar = "خطر متوسط"

    risk_message = (
        "الظروف الحالية تشير إلى احتمال متوسط لحدوث حريق."
    )

    risk_class = "medium-risk"
    emoji = "🟡"
    gauge_color = "#f59e0b"

else:

    risk_level = "HIGH RISK"
    risk_ar = "خطر مرتفع"

    risk_message = (
        "الظروف الحالية تشير إلى احتمالية مرتفعة للحريق."
    )

    risk_class = "high-risk"
    emoji = "🔴"
    gauge_color = "#ef4444"

# Convert probability to percentage
probability_percent = fire_probability * 100

# 27. Final UI Polish and Reset

In this stage, we finalize the user interface by improving
the input experience and providing a reset option.

### Steps:
1. Start the date field empty.
2. Validate the entered date before prediction.
3. Allow the user to clear all inputs and start a new prediction.

In [66]:
# Find a real test case with Medium Risk probability
# Medium Risk = 30% to less than 75%

# Get Fire probabilities for all test samples
test_probabilities = xgb_top10_pipeline.predict_proba(
    X_test_top10
)[:, 1]

# Create a table containing the test samples and their probabilities
medium_cases = X_test_top10.copy()
medium_cases["Fire_Probability"] = test_probabilities

# Keep only cases in the Medium Risk range
medium_cases = medium_cases[
    (medium_cases["Fire_Probability"] >= 0.30) &
    (medium_cases["Fire_Probability"] < 0.75)
].copy()

# Sort by probability closest to 50%
medium_cases["Distance_From_50"] = (
    medium_cases["Fire_Probability"] - 0.50
).abs()

medium_case = medium_cases.sort_values(
    "Distance_From_50"
).head(1)

# Display the result
print("===== Real Medium Risk Case =====")

if len(medium_case) > 0:

    probability = medium_case["Fire_Probability"].iloc[0]

    print(f"Fire Probability: {probability:.2%}")
    print("Risk Level: MEDIUM RISK")

    print("\n===== Input Values =====")
    print(
        medium_case[
            [
                "precmax",
                "precsum",
                "precmin",
                "ndvimedian",
                "ndwimin",
                "days",
                "latitude",
                "slope",
                "year",
                "day_of_year"
            ]
        ].T
    )

else:
    print("No Medium Risk case was found.")

===== Real Medium Risk Case =====
Fire Probability: 49.87%
Risk Level: MEDIUM RISK

===== Input Values =====
                    1083
precmax         9.914841
precsum        22.563084
precmin         0.000000
ndvimedian      0.488736
ndwimin        -0.078668
days           12.000000
latitude       25.325754
slope           7.121574
year         2016.000000
day_of_year    63.000000